# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '15.4'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'
  pod 'GoogleMaps', '9.1.0'
  pod 'GooglePlaces', '8.2.0'
  pod 'Google-Maps-iOS-Utils', '6.0.0'
end
